### ISSUE TITLE
Cannot use List Blobs node Step

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck-plugins/rundeck-azure-storage-plugin#1]
With all the required packages installed, I got the following error:

```
Traceback (most recent call last):
  File "/home/rundeck/rundeck/libext/cache/rundeck-azure-storage-plugin-1.0.1/azure-ls.py", line 1, in <module>
    import azure.common
ImportError: No module named common
Failed: NonZeroResultCode: Script result code was: 1
Execution failed: 19 in project ExampleAzureProject: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [node01-6c: NonZeroResultCode: Script result code was: 1 + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {node01-6c=[NonZeroResultCode: Script result code was: 1 + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]
```

So, I installed the azure-common package using pip, and I got the following message:

```
Traceback (most recent call last):
  File "/home/rundeck/rundeck/libext/cache/rundeck-azure-storage-plugin-1.0.1/azure-ls.py", line 6, in <module>
    from azure.storage import CloudStorageAccount
ImportError: cannot import name CloudStorageAccount
Failed: NonZeroResultCode: Script result code was: 1
Execution failed: 20 in project ExampleAzureProject: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [node01-6c: NonZeroResultCode: Script result code was: 1 + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {node01-6c=[NonZeroResultCode: Script result code was: 1 + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]
```

From there, I've tried to install azure-storage-common with the same result.

**Comment by jbanda15** [comment]
This happened to me in Rundeck 3.3.0-rc1, I got the same output with the list, remove and remote copy: 

`Traceback (most recent call last):
  File "/home/jason/Rundeck/versions/3/3.3-rc1/libext/cache/rundeck-azure-storage-plugin-1.0.1/azure-ls.py", line 1, in <module>
    import azure.common
ImportError: No module named azure.common
Failed: NonZeroResultCode: Script result code was: 1`

`Traceback (most recent call last):
  File "/home/jason/Rundeck/versions/3/3.3-rc1/libext/cache/rundeck-azure-storage-plugin-1.0.1/azure-rm.py", line 1, in <module>
    import azure.common
ImportError: No module named azure.common
Failed: NonZeroResultCode: Script result code was: 1`

`Traceback (most recent call last):
  File "/tmp/1-10930-jb-asus-azure-cp.py", line 5, in <module>
    import azure.common
ImportError: No module named azure.common
Result: 1
Failed: NonZeroResultCode: Result code was 1`

**Comment by ltamaster** [comment]
fix with https://github.com/rundeck-plugins/rundeck-azure-storage-plugin/pull/2
